package service;

public enum ActionsEnum {
	APPLICATION_LOGIN, //UC0
	PERSONNAL_DETAILS, //UC1, UC2, UC3
	MEMBER_DETAIL, //UC4
	MEMBER_LIST, //UC4
	PARTNER_LIST, //UC5
	PROJECT_LIST, //UC6
	REWARD_PERSONAL, //UC8
	ACTIVITY_LIST, //UC9
	ACTIVITY_ENROLLMENT, //UC10
	ACTIVITY_MANAGEMENT, //UC11
	PARTNER_DETAIL, //UC12
	PARTNER_MANAGEMENT, //UC13
	PROJECT_DETAIL, //UC14, UC17
	PROJECT_MANAGEMENT, //UC15
	REWARD_LIST, //UC16
	PROJECT_EDIT, //UC23
	ADMINISTRATION_MEMBER, //UC24
	ADMINISTRATION_ENUMERATION //UC25
}
