# --- !Ups
INSERT INTO sqa_user (id, version, visible, bio, degree, email, firstname, lastname, password, phonenumber, username, stateuser_stateuserid) VALUES (1, 4, true, NULL, 'Bc', 'email@email.cz', 'Jan', 'Admin', '$2a$10$ZVvN9jMJpNL/BWuXF/1Is.B6U2z/DK/YVSCasZCv3y1rcvoEUTj9.', '123456789', 'admin', 1);
INSERT INTO sqa_user (id, version, visible, bio, degree, email, firstname, lastname, password, phonenumber, username, stateuser_stateuserid) VALUES (2, 3, true, NULL, '', '', 'Karel', 'Vedouci', '$2a$10$DKslzWrwIAfI8GntNuSmReZOxdi0lSkr9SehegAu09a/O1jz5.xYO', '', 'head',  1);
INSERT INTO sqa_user (id, version, visible, bio, degree, email, firstname, lastname, password, phonenumber, username, stateuser_stateuserid) VALUES (3, 3, true, NULL, '', '', 'Filip', 'Manazer', '$2a$10$j8OJMlz6DCLlpMEyrBtsiuRW23DC2DlbO8nLPav3BNo4tzSSZFYqa', '', 'manager',  1);
INSERT INTO sqa_user (id, version, visible, bio, degree, email, firstname, lastname, password, phonenumber, username, stateuser_stateuserid) VALUES (4, 6, true, NULL, '', '', 'Dominik', 'Clen', '$2a$10$CIPJCOC.4QPY4PrgX9SwBe22Lcgidowm9IRSnnteAOWYq0pfnJfVO', '', 'member',  1);
INSERT INTO sqa_user (id, version, visible, bio, degree, email, firstname, lastname, password, phonenumber, username, stateuser_stateuserid) VALUES (5, 1, true, NULL, NULL, NULL, 'Tomas', 'Michalicka', '$2a$10$psXmzcV.OAa7GnIW4S/mjOnMLQxgYjG6WMN7/h9BVmRZS.TIwG2my', NULL, 'tomas',  1);
INSERT INTO sqa_user (id, version, visible, bio, degree, email, firstname, lastname, password, phonenumber, username, stateuser_stateuserid) VALUES (6, 3, true, NULL, 'Bc', 'jira03@vse.cz', 'Ales', 'Jiranek', '$2a$10$025pppYseCQJLwsk6g4VLeXUxWoYLW7bGSP3yebhMg.qeDso4wuX6', '123456789', 'ales', 1);
INSERT INTO sqa_user (id, version, visible, bio, degree, email, firstname, lastname, password, phonenumber, username, stateuser_stateuserid) VALUES (7, 2, true, NULL, '', '', 'Jan', 'Petr', '$2a$10$BWuGWqecHz.R0YKcUbM17uhXsYS3eB.DravBqVBEH/YU0uOSA7LeG', '', 'petr', 1);
INSERT INTO sqa_user (id, version, visible, bio, degree, email, firstname, lastname, password, phonenumber, username, stateuser_stateuserid) VALUES (8, 4, true, NULL, '', 'test@email.com', 'Miroslav', 'Cech', '$2a$10$QX6IVAXhjRC7JA3NJPStSetmQTLCWuQSBQ0UuAzAkDlLFYxGWNfUO', '+420123123123', 'miroslav', 1);
INSERT INTO sqa_user (id, version, visible, bio, degree, email, firstname, lastname, password, phonenumber, username, stateuser_stateuserid) VALUES (9, 2, true, NULL, '', '', 'Jiri', 'Siroky', '$2a$10$RHOxgfH4prDfbfsAjbEW4OIWbahn5fSbU5g3l8IBT5qJeUahwtXXa', '', 'jiri', 1);
INSERT INTO sqa_user (id, version, visible, bio, degree, email, firstname, lastname, password, phonenumber, username, stateuser_stateuserid) VALUES (10, 2, true, NULL, '', '', 'Ondrej', 'Kostal', '$2a$10$BE3jTHMt9oj2yifgr9SDKOqlynlH99QutRRd7uWXyqLGW2mtgaBoC', '', 'ondrej', 1);
INSERT INTO sqa_user (id, version, visible, bio, degree, email, firstname, lastname, password, phonenumber, username, stateuser_stateuserid) VALUES (11, 35, true, NULL, 'JUDr', 'nic@nereknu.ne', 'Radek', 'Slavětínský', '$2a$10$aV.UOuDyrccWquSOOX3uRuVmCY3WJc0GxyxIqNcIYvO69Ig/MBAyO', '777777777', 'radek', 1);
INSERT INTO sqa_user (id, version, visible, bio, degree, email, firstname, lastname, password, phonenumber, username, stateuser_stateuserid) VALUES (12, 5, true, NULL, '', '', 'Vladimir', 'Rahm', '$2a$10$N7mR0HwtUMKlsT8VXx3y/.QJEJRhKWKrn.1BzG4txnyyh1BM2lGWa', '', 'vladimir', 1);
INSERT INTO sqa_user (id, version, visible, bio, degree, email, firstname, lastname, password, phonenumber, username, stateuser_stateuserid) VALUES (13, 6, true, NULL, 'borec', 'email@email.cz', 'Jan', 'Smetana', '$2a$10$QbqPAfrNebYCFBkHMBj/GOYAVbkluyVkg6lVGhsFGaSRvXvcA3DRK', '888888888', 'jan',  1);
INSERT INTO sqa_user (id, version, visible, bio, degree, email, firstname, lastname, password, phonenumber, username, stateuser_stateuserid) VALUES (137, 5, false, NULL, 'JUDr', 'test@judr.new', 'TestJméno', 'TestPříjmení', '$2a$10$rFtFxk3vLB3unRmIv4sozus25BWrHwK7T/.QcfU4ywbGN0pVwRPgK', '777123456', NULL,  1);
INSERT INTO sqa_user (id, version, visible, bio, degree, email, firstname, lastname, password, phonenumber, username, stateuser_stateuserid) VALUES (167, 6, false, NULL, 'MUDr', 'petrkadlec.net@test.net', 'Arnoldík', 'Schwarzburger', '$2a$10$bTEXIX0Xed8Tpl/qeVhnHugyqw99Z2liBQNfxV2AhMAW5NSBLNwze', '321321321', 'arnold', 0);
INSERT INTO sqa_user (id, version, visible, bio, degree, email, firstname, lastname, password, phonenumber, username, stateuser_stateuserid) VALUES (193, 3, false, NULL, 'Bc.', '', 'Han', 'Solo', '$2a$10$4PsOpQWQkognHfB.s2CxfuPdA7pILFDrU/Xaw1KamzwSJziSMxWy2', '', 'hansolo', 1);
INSERT INTO sqa_user (id, version, visible, bio, degree, email, firstname, lastname, password, phonenumber, username, stateuser_stateuserid) VALUES (194, 1, true, NULL, '', '', 'Anakin', 'Skywalker', '$2a$10$VC.dm4knzTiZqPGbpe/IyOnEuihORyjXCcbTTlgDq1N1F2gdlEvIS', '', 'anakin', 1);
INSERT INTO sqa_user (id, version, visible, bio, degree, email, firstname, lastname, password, phonenumber, username, stateuser_stateuserid) VALUES (200, 1, true, NULL, 'Ing', 'stojan@seznam.cz', 'Stojan', 'Jakotyc', '$2a$10$AeQQ.tojwGs57SxH4HHHWep0fbNjv9.hBHAwMqxP3BmW5NNlttptW', '+420123123123', 'stojan', 1);
INSERT INTO sqa_user (id, version, visible, bio, degree, email, firstname, lastname, password, phonenumber, username, stateuser_stateuserid) VALUES (209, 3, true, NULL, 'RNDr', 'franta@vsechnyzmalim.vz', 'Franta', 'Mlátička', 'testtest', '55555555', 'test', 1);
INSERT INTO sqa_user (id, version, visible, bio, degree, email, firstname, lastname, password, phonenumber, username, stateuser_stateuserid) VALUES (258, 2, false, NULL, 'xXx', '', 'TestJméno', 'TestPříjmení', '$2a$10$O3uc.kwTwwWyivgt9.i3xeE3rCD9vQVkMgTcHVALdF749w7EuSQ/u', '', 'test', 1);

# --- !Downs

DELETE FROM sqa_user;