language: java
env:
  - ACTIVATOR_BIN=${TRAVIS_BUILD_DIR}/activator
script:
  - "cd $TRAVIS_BUILD_DIR && ${ACTIVATOR_BIN} test"
notifications:
  # Email notifications are disabled to not annoy anybody.
  email: false